name: "Run WeChat-MP Crawler"
on:
  workflow_dispatch:

jobs:
  python_test:
    name: "Run python script"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Set up python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: 'pip'
      - name: "Install dependencies"
        run: pip install -r requirements.txt
      - name: "Run python script"
        run: |
          python main.py
        env:
          CTRL_START: ${{ secrets.CTRL_START }}
          CTRL_END: ${{ secrets.CTRL_END }}
          MP_COOKIE: ${{ secrets.MP_COOKIE }}
          MP_TOKEN: ${{ secrets.MP_TOKEN }}
          TARGET_FAKEID: ${{ secrets.TARGET_FAKEID }}
          WECHAT_COOKIE: ${{ secrets.WECHAT_COOKIE }}
          WECHAT_KEY: ${{ secrets.WECHAT_KEY }}
          WECHAT_PASS: ${{ secrets.WECHAT_PASS }}
          WECHAT_TOKEN: ${{ secrets.WECHAT_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3