name: "Run WeChat-MP Crawler"
on:
  workflow_dispatch:

jobs:
  python_test:
    name: "Run python script"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Set up python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: 'pip'
      - name: "Install dependencies"
        run: pip install -r requirements.txt
      - name: "Run python script"
        run: |
          python wechatmp_crawler.py
        env:
          CTRL_START: ${{ secrets.CTRL_START }}
          CTRL_END: ${{ secrets.CTRL_END }}
          MP_MANAGE_COOKIE: ${{ secrets.MP_MANAGE_COOKIE }}
          MP_MANAGE_FAKEID: ${{ secrets.MP_MANAGE_FAKEID }}
          MP_READER_COOKIE: ${{ secrets.MP_READER_COOKIE }}
          MP_READER_KEY: ${{ secrets.MP_READER_KEY }}
          MP_READER_PASS: ${{ secrets.MP_READER_PASS }}
          MP_READER_TOKEN: ${{ secrets.MP_READER_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3